apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-hello-world
  template:
    metadata:
      labels:
        app: kube-hello-world
    spec:
      containers:
      - name: kube-hello-world
        image: localhost:5000/kube-hello-world
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"